# Generated by Django 2.0.1 on 2018-12-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaticfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobno',
            field=models.CharField(default='', max_length=13),
        ),
    ]
